import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import useAuth from "../hooks/useAuth";
import requests from "../utils/requests";
import { useRecoilValue } from "recoil";
import { modalState } from "../atoms/modalAtom";
import Modal from "../components/Modal";

export default function Home({ results }) {
	const { loading } = useAuth();
	const showModal = useRecoilValue(modalState);

	return !loading ? (
		<div
			className={`relative h-screen bg-gradient-to-b lg:h-[141vh] ${
				showModal && `!h-screen overflow-y-hidden`
			}`}
		>
			<Head>
				<title>Hulu</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Header />
				<Nav />
				<Results results={results} />
			</main>
			{showModal && <Modal />}
		</div>
	) : null;
}

export const getServerSideProps = async (context) => {
	const genre = context.query.genre;

	const request = await fetch(
		`https://api.themoviedb.org/3${
			requests[genre]?.url || requests.fetchTrending.url
		}`
	).then((res) => res.json());
	return {
		props: {
			results: request.results,
		},
	};
};
